services:
  hapi-template-ts:
    extends:
      file: docker-compose.yaml
      service: hapi-template-ts
    build:
      target: development
    image: hapi-template-ts-test
    container_name: hapi-template-ts-test
    command: npm run test
    volumes:
      - ./src:/home/node/src
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./package.json:/home/node/package.json
      - ./eslint.config.js:/home/node/eslint.config.js
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
